name: CI

on: [push, pull_request]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.31
      - name: Install Dependencies
        run: bun install
      - name: Run tests
        run: bun run test

  build:
    name: Build and Artifact Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.0.31
      - name: Install Dependencies
        run: bun install
      - name: Build and Extract WASM
        run: |
          7z x wasm.zip
          mkdir ./wasm
          mv ./kaspa-wasm32-sdk/web/kaspa/* ./wasm
          bun run build
      - name: Upload Dist as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: unpacked-extension
          path: dist/
