name: CI

on: [push, pull_request]

jobs:
  build:
    name: Build and Artifact Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use bun
        uses: oven-sh/setup-bun@v2
      - name: Install Dependencies
        run: bun install
      - name: Build
        run: bun run build
